spring:
    datasource:
        datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:mem:inventorydb
        username: sa
        initialization-mode: always
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
